Metrics/LineLength:
  Max: 180

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 30

Style/AsciiComments:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Style/FormatString:
  EnforcedStyle: percent

Style/Documentation:
  Enabled: false

Style/Next:
  Enabled: false

