Metrics/AbcSize:
  Max: 35

Metrics/LineLength:
  Max: 120

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Style/FormatString:
  EnforcedStyle: percent

Style/Next:
  Enabled: false
